name: Build EXE

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        pip install -e .
    
    - name: Build EXE
      run: |
        pwd
        dir
        if (Test-Path "../icon.ico") {
            Copy-Item "../icon.ico" -Destination "."
        }
        dir
        pyinstaller --onefile --windowed --name videoxt `
            --add-data "src/videoxt;videoxt" `
            --clean `
            --noconfirm `
            --uac-admin `
            --version-file version.txt `
            --icon="icon.ico" `
            run_gui.py
        dir dist
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: videoxt
        path: dist/videoxt.exe

    - name: Debug Info
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "GitHub ref name: ${{ github.ref_name }}"
        echo "GitHub event name: ${{ github.event_name }}"
        echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"
        dir dist

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/videoxt.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          Release ${{ github.ref_name }}
          
          Changes in this release:
          - See commit history for details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 